language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: B3dhrVLSEB5rcwLCquw6+NfIal54u2v8zWFnonmdowlZRLSgIXOuVP1jbX5Vdj+qBiTf5U33STd3+J9XlKrMcdfAtZ92e7GZHHqXDt1UNskJ4aThlWSRMa5ldZee8/AoSyUc8xlehkUBgCWH5esJzlNIm6cvZ6IiSMuOayFyL+b9sq5p6m/yAouaNTsrNgwPRR/8XAZ15TzHOCXGHlZNWfO5+DgazWIJfR818QKMkuk6sHkQPpSX9F00P69pZShQ+oErS9ySeXZzpGKPBocxyalUrZG39WPvAWsRHqh4zjWn/c25TclcXUJUBEVlTg1omDWzgXFZxdHAgiv39FzNbdpfF5BQJmdbSYDnbg9jQ53MNZSymZWOhWfDeNVP2vRXOewuJPEp5nJuT5WYK9Hl+ag7bDT+Va8aT33bcsR805hIo3i/PXdqBjfCcBHvYQwLMZ1eJATiazw+FP+RnNKlqcdcrW1GMv2LAzOGZTmcQ4DaxSg7ux1EU6TV1TLNKsaV6DwILw8DSOyYlr2VvGRpakKJtqlCoLrxTNOSeQbGDiZhKkvjzxCX/dZhn+Cd/TosKlMuZXSSLgWarpatQxu9cJFiYY2gkb2m9iLBWgrgZJ7ZvsecZMrTI+pkbL/pDfF3GiaCazcP4kwcHsRM60ZzOo8uvvuoXIUNb9IRrEK2X4U=
  app: cryptic-sierra-39000
  on:
    repo: patelpr/node-shopping-list-integration-tests
